// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package firehydrantgosdk

// Generated from OpenAPI doc version 0.0.1 and generator version 2.938.0

import (
	"context"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/config"
	"github.com/firehydrant/firehydrant-go-sdk/internal/hooks"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
	"github.com/firehydrant/firehydrant-go-sdk/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	"https://api.firehydrant.io/",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

type FireHydrant struct {
	SDKVersion string
	// Operations related to Account Settings
	AccountSettings *AccountSettings
	// Operations related to Catalog Entries
	CatalogEntries *CatalogEntries
	// Operations related to Teams
	Teams *Teams
	// Operations related to Signals
	Signals *Signals
	// Operations about Call Routes
	CallRoutes *CallRoutes
	// Operations related to Changes
	Changes *Changes
	// Operations related to Incidents
	Incidents *Incidents
	// Operations related to Alerts
	Alerts *Alerts
	// Operations related to Status Pages
	StatusPages *StatusPages
	// Operations related to Tasks
	Tasks *Tasks
	// Operations related to Conversations
	Conversations *Conversations
	// Operations related to Retrospectives
	Retrospectives *Retrospectives
	// Operations related to Incident Settings
	IncidentSettings *IncidentSettings
	// Operations related to Integrations
	Integrations *Integrations
	// Operations related to Users
	Users *Users
	// Operations about Permissions
	Permissions *Permissions
	// Operations related to Metrics & Reporting
	MetricsReporting *MetricsReporting
	// Operations about Roles
	Roles *Roles
	// Operations related to Runbooks
	Runbooks *Runbooks
	// Operations about Audit Events
	AuditEvents *AuditEvents
	// Operations related to Communication
	Communication *Communication
	// Operations about Pages
	Pages *Pages
	// Operations related to Ticketing
	Ticketing *Ticketing
	// Operations related to SCIM
	Scim *Scim
	// Operations related to Webhooks
	Webhooks *Webhooks
	// Operations related to Audiences
	Audiences *Audiences

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*FireHydrant)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *FireHydrant) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *FireHydrant) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *FireHydrant) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *FireHydrant {
	sdk := &FireHydrant{
		SDKVersion: "1.9.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:         "speakeasy-sdk/go 1.9.0 2.938.0 0.0.1 github.com/firehydrant/firehydrant-go-sdk",
			SDKVersion:        "1.9.0",
			GenVersion:        "2.938.0",
			OpenAPIDocVersion: "0.0.1",
			ServerList:        ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	currentServerURL, _ := sdk.sdkConfiguration.GetServerDetails()
	serverURL := currentServerURL
	serverURL, sdk.sdkConfiguration.Client = sdk.hooks.SDKInit(currentServerURL, sdk.sdkConfiguration.Client)
	if currentServerURL != serverURL {
		sdk.sdkConfiguration.ServerURL = serverURL
	}

	sdk.AccountSettings = newAccountSettings(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CatalogEntries = newCatalogEntries(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Teams = newTeams(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Signals = newSignals(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CallRoutes = newCallRoutes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Changes = newChanges(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Incidents = newIncidents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Alerts = newAlerts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.StatusPages = newStatusPages(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tasks = newTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Conversations = newConversations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Retrospectives = newRetrospectives(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.IncidentSettings = newIncidentSettings(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Integrations = newIntegrations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Users = newUsers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Permissions = newPermissions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.MetricsReporting = newMetricsReporting(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Roles = newRoles(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Runbooks = newRunbooks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.AuditEvents = newAuditEvents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Communication = newCommunication(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Pages = newPages(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Ticketing = newTicketing(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Scim = newScim(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Webhooks = newWebhooks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Audiences = newAudiences(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
