// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteSupportHoursScheduleRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
}

func (d *DeleteSupportHoursScheduleRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}
