// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// GetSignalsGroupedMetricsGroupBy - String that determines how records are grouped
type GetSignalsGroupedMetricsGroupBy string

const (
	GetSignalsGroupedMetricsGroupBySignalRules  GetSignalsGroupedMetricsGroupBy = "signal_rules"
	GetSignalsGroupedMetricsGroupByTeams        GetSignalsGroupedMetricsGroupBy = "teams"
	GetSignalsGroupedMetricsGroupByServices     GetSignalsGroupedMetricsGroupBy = "services"
	GetSignalsGroupedMetricsGroupByEnvironments GetSignalsGroupedMetricsGroupBy = "environments"
	GetSignalsGroupedMetricsGroupByTags         GetSignalsGroupedMetricsGroupBy = "tags"
)

func (e GetSignalsGroupedMetricsGroupBy) ToPointer() *GetSignalsGroupedMetricsGroupBy {
	return &e
}
func (e *GetSignalsGroupedMetricsGroupBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "signal_rules":
		fallthrough
	case "teams":
		fallthrough
	case "services":
		fallthrough
	case "environments":
		fallthrough
	case "tags":
		*e = GetSignalsGroupedMetricsGroupBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsGroupedMetricsGroupBy: %v", v)
	}
}

// GetSignalsGroupedMetricsSortBy - String that determines how records are sorted
type GetSignalsGroupedMetricsSortBy string

const (
	GetSignalsGroupedMetricsSortByTotalOpenedAlerts   GetSignalsGroupedMetricsSortBy = "total_opened_alerts"
	GetSignalsGroupedMetricsSortByTotalAckedAlerts    GetSignalsGroupedMetricsSortBy = "total_acked_alerts"
	GetSignalsGroupedMetricsSortByTotalIncidents      GetSignalsGroupedMetricsSortBy = "total_incidents"
	GetSignalsGroupedMetricsSortByTotalBillableAlerts GetSignalsGroupedMetricsSortBy = "total_billable_alerts"
	GetSignalsGroupedMetricsSortByTotalResolvedAlerts GetSignalsGroupedMetricsSortBy = "total_resolved_alerts"
	GetSignalsGroupedMetricsSortByAckedPercentage     GetSignalsGroupedMetricsSortBy = "acked_percentage"
	GetSignalsGroupedMetricsSortByIncidentsPercentage GetSignalsGroupedMetricsSortBy = "incidents_percentage"
)

func (e GetSignalsGroupedMetricsSortBy) ToPointer() *GetSignalsGroupedMetricsSortBy {
	return &e
}
func (e *GetSignalsGroupedMetricsSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "total_opened_alerts":
		fallthrough
	case "total_acked_alerts":
		fallthrough
	case "total_incidents":
		fallthrough
	case "total_billable_alerts":
		fallthrough
	case "total_resolved_alerts":
		fallthrough
	case "acked_percentage":
		fallthrough
	case "incidents_percentage":
		*e = GetSignalsGroupedMetricsSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsGroupedMetricsSortBy: %v", v)
	}
}

// GetSignalsGroupedMetricsSortDirection - String that determines how records are sorted
type GetSignalsGroupedMetricsSortDirection string

const (
	GetSignalsGroupedMetricsSortDirectionAsc  GetSignalsGroupedMetricsSortDirection = "asc"
	GetSignalsGroupedMetricsSortDirectionDesc GetSignalsGroupedMetricsSortDirection = "desc"
)

func (e GetSignalsGroupedMetricsSortDirection) ToPointer() *GetSignalsGroupedMetricsSortDirection {
	return &e
}
func (e *GetSignalsGroupedMetricsSortDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GetSignalsGroupedMetricsSortDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsGroupedMetricsSortDirection: %v", v)
	}
}

type GetSignalsGroupedMetricsRequest struct {
	// A comma separated list of signal rule IDs
	SignalRules *string `queryParam:"style=form,explode=true,name=signal_rules"`
	// A comma separated list of team IDs
	Teams *string `queryParam:"style=form,explode=true,name=teams"`
	// A comma separated list of environment IDs
	Environments *string `queryParam:"style=form,explode=true,name=environments"`
	// A comma separated list of service IDs
	Services *string `queryParam:"style=form,explode=true,name=services"`
	// A comma separated list of tags
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
	// A comma separated list of user IDs
	Users *string `queryParam:"style=form,explode=true,name=users"`
	// String that determines how records are grouped
	GroupBy *GetSignalsGroupedMetricsGroupBy `queryParam:"style=form,explode=true,name=group_by"`
	// String that determines how records are sorted
	SortBy *GetSignalsGroupedMetricsSortBy `queryParam:"style=form,explode=true,name=sort_by"`
	// String that determines how records are sorted
	SortDirection *GetSignalsGroupedMetricsSortDirection `queryParam:"style=form,explode=true,name=sort_direction"`
	// The start date to return metrics from
	StartDate *time.Time `queryParam:"style=form,explode=true,name=start_date"`
	// The end date to return metrics from
	EndDate *time.Time `queryParam:"style=form,explode=true,name=end_date"`
}

func (g GetSignalsGroupedMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSignalsGroupedMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSignalsGroupedMetricsRequest) GetSignalRules() *string {
	if g == nil {
		return nil
	}
	return g.SignalRules
}

func (g *GetSignalsGroupedMetricsRequest) GetTeams() *string {
	if g == nil {
		return nil
	}
	return g.Teams
}

func (g *GetSignalsGroupedMetricsRequest) GetEnvironments() *string {
	if g == nil {
		return nil
	}
	return g.Environments
}

func (g *GetSignalsGroupedMetricsRequest) GetServices() *string {
	if g == nil {
		return nil
	}
	return g.Services
}

func (g *GetSignalsGroupedMetricsRequest) GetTags() *string {
	if g == nil {
		return nil
	}
	return g.Tags
}

func (g *GetSignalsGroupedMetricsRequest) GetUsers() *string {
	if g == nil {
		return nil
	}
	return g.Users
}

func (g *GetSignalsGroupedMetricsRequest) GetGroupBy() *GetSignalsGroupedMetricsGroupBy {
	if g == nil {
		return nil
	}
	return g.GroupBy
}

func (g *GetSignalsGroupedMetricsRequest) GetSortBy() *GetSignalsGroupedMetricsSortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetSignalsGroupedMetricsRequest) GetSortDirection() *GetSignalsGroupedMetricsSortDirection {
	if g == nil {
		return nil
	}
	return g.SortDirection
}

func (g *GetSignalsGroupedMetricsRequest) GetStartDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetSignalsGroupedMetricsRequest) GetEndDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.EndDate
}
