// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetSupportHoursScheduleRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
}

func (g *GetSupportHoursScheduleRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}
