// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// GetSignalsTimeseriesAnalyticsBucket - String that determines how records are grouped
type GetSignalsTimeseriesAnalyticsBucket string

const (
	GetSignalsTimeseriesAnalyticsBucketMonth GetSignalsTimeseriesAnalyticsBucket = "month"
	GetSignalsTimeseriesAnalyticsBucketWeek  GetSignalsTimeseriesAnalyticsBucket = "week"
	GetSignalsTimeseriesAnalyticsBucketDay   GetSignalsTimeseriesAnalyticsBucket = "day"
)

func (e GetSignalsTimeseriesAnalyticsBucket) ToPointer() *GetSignalsTimeseriesAnalyticsBucket {
	return &e
}
func (e *GetSignalsTimeseriesAnalyticsBucket) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "month":
		fallthrough
	case "week":
		fallthrough
	case "day":
		*e = GetSignalsTimeseriesAnalyticsBucket(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsTimeseriesAnalyticsBucket: %v", v)
	}
}

// GetSignalsTimeseriesAnalyticsGroupBy - String that determines how records are grouped
type GetSignalsTimeseriesAnalyticsGroupBy string

const (
	GetSignalsTimeseriesAnalyticsGroupBySignalRules  GetSignalsTimeseriesAnalyticsGroupBy = "signal_rules"
	GetSignalsTimeseriesAnalyticsGroupByTeams        GetSignalsTimeseriesAnalyticsGroupBy = "teams"
	GetSignalsTimeseriesAnalyticsGroupByServices     GetSignalsTimeseriesAnalyticsGroupBy = "services"
	GetSignalsTimeseriesAnalyticsGroupByEnvironments GetSignalsTimeseriesAnalyticsGroupBy = "environments"
	GetSignalsTimeseriesAnalyticsGroupByTags         GetSignalsTimeseriesAnalyticsGroupBy = "tags"
)

func (e GetSignalsTimeseriesAnalyticsGroupBy) ToPointer() *GetSignalsTimeseriesAnalyticsGroupBy {
	return &e
}
func (e *GetSignalsTimeseriesAnalyticsGroupBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "signal_rules":
		fallthrough
	case "teams":
		fallthrough
	case "services":
		fallthrough
	case "environments":
		fallthrough
	case "tags":
		*e = GetSignalsTimeseriesAnalyticsGroupBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsTimeseriesAnalyticsGroupBy: %v", v)
	}
}

// GetSignalsTimeseriesAnalyticsSortBy - String that determines how records are sorted
type GetSignalsTimeseriesAnalyticsSortBy string

const (
	GetSignalsTimeseriesAnalyticsSortByTotalOpenedAlerts   GetSignalsTimeseriesAnalyticsSortBy = "total_opened_alerts"
	GetSignalsTimeseriesAnalyticsSortByTotalAckedAlerts    GetSignalsTimeseriesAnalyticsSortBy = "total_acked_alerts"
	GetSignalsTimeseriesAnalyticsSortByTotalIncidents      GetSignalsTimeseriesAnalyticsSortBy = "total_incidents"
	GetSignalsTimeseriesAnalyticsSortByTotalBillableAlerts GetSignalsTimeseriesAnalyticsSortBy = "total_billable_alerts"
	GetSignalsTimeseriesAnalyticsSortByTotalResolvedAlerts GetSignalsTimeseriesAnalyticsSortBy = "total_resolved_alerts"
	GetSignalsTimeseriesAnalyticsSortByAckedPercentage     GetSignalsTimeseriesAnalyticsSortBy = "acked_percentage"
	GetSignalsTimeseriesAnalyticsSortByIncidentsPercentage GetSignalsTimeseriesAnalyticsSortBy = "incidents_percentage"
)

func (e GetSignalsTimeseriesAnalyticsSortBy) ToPointer() *GetSignalsTimeseriesAnalyticsSortBy {
	return &e
}
func (e *GetSignalsTimeseriesAnalyticsSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "total_opened_alerts":
		fallthrough
	case "total_acked_alerts":
		fallthrough
	case "total_incidents":
		fallthrough
	case "total_billable_alerts":
		fallthrough
	case "total_resolved_alerts":
		fallthrough
	case "acked_percentage":
		fallthrough
	case "incidents_percentage":
		*e = GetSignalsTimeseriesAnalyticsSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsTimeseriesAnalyticsSortBy: %v", v)
	}
}

// GetSignalsTimeseriesAnalyticsSortDirection - String that determines how records are sorted
type GetSignalsTimeseriesAnalyticsSortDirection string

const (
	GetSignalsTimeseriesAnalyticsSortDirectionAsc  GetSignalsTimeseriesAnalyticsSortDirection = "asc"
	GetSignalsTimeseriesAnalyticsSortDirectionDesc GetSignalsTimeseriesAnalyticsSortDirection = "desc"
)

func (e GetSignalsTimeseriesAnalyticsSortDirection) ToPointer() *GetSignalsTimeseriesAnalyticsSortDirection {
	return &e
}
func (e *GetSignalsTimeseriesAnalyticsSortDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GetSignalsTimeseriesAnalyticsSortDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSignalsTimeseriesAnalyticsSortDirection: %v", v)
	}
}

type GetSignalsTimeseriesAnalyticsRequest struct {
	// String that determines how records are grouped
	Bucket *GetSignalsTimeseriesAnalyticsBucket `queryParam:"style=form,explode=true,name=bucket"`
	// A comma separated list of signal rule IDs
	SignalRules *string `queryParam:"style=form,explode=true,name=signal_rules"`
	// A comma separated list of team IDs
	Teams *string `queryParam:"style=form,explode=true,name=teams"`
	// A comma separated list of environment IDs
	Environments *string `queryParam:"style=form,explode=true,name=environments"`
	// A comma separated list of service IDs
	Services *string `queryParam:"style=form,explode=true,name=services"`
	// A comma separated list of tags
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
	// A comma separated list of user IDs
	Users *string `queryParam:"style=form,explode=true,name=users"`
	// String that determines how records are grouped
	GroupBy *GetSignalsTimeseriesAnalyticsGroupBy `queryParam:"style=form,explode=true,name=group_by"`
	// String that determines how records are sorted
	SortBy *GetSignalsTimeseriesAnalyticsSortBy `queryParam:"style=form,explode=true,name=sort_by"`
	// String that determines how records are sorted
	SortDirection *GetSignalsTimeseriesAnalyticsSortDirection `queryParam:"style=form,explode=true,name=sort_direction"`
	// The start date to return metrics from
	StartDate *time.Time `queryParam:"style=form,explode=true,name=start_date"`
	// The end date to return metrics from
	EndDate *time.Time `queryParam:"style=form,explode=true,name=end_date"`
}

func (g GetSignalsTimeseriesAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSignalsTimeseriesAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetBucket() *GetSignalsTimeseriesAnalyticsBucket {
	if g == nil {
		return nil
	}
	return g.Bucket
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetSignalRules() *string {
	if g == nil {
		return nil
	}
	return g.SignalRules
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetTeams() *string {
	if g == nil {
		return nil
	}
	return g.Teams
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetEnvironments() *string {
	if g == nil {
		return nil
	}
	return g.Environments
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetServices() *string {
	if g == nil {
		return nil
	}
	return g.Services
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetTags() *string {
	if g == nil {
		return nil
	}
	return g.Tags
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetUsers() *string {
	if g == nil {
		return nil
	}
	return g.Users
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetGroupBy() *GetSignalsTimeseriesAnalyticsGroupBy {
	if g == nil {
		return nil
	}
	return g.GroupBy
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetSortBy() *GetSignalsTimeseriesAnalyticsSortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetSortDirection() *GetSignalsTimeseriesAnalyticsSortDirection {
	if g == nil {
		return nil
	}
	return g.SortDirection
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetStartDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetSignalsTimeseriesAnalyticsRequest) GetEndDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.EndDate
}
