// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// ListAlertsTagMatchStrategy - The strategy to match tags. `any` will return alerts that have at least one of the supplied tags, `match_all` will return only alerts that have all of the supplied tags, and `exclude` will only return alerts that have none of the supplied tags. This currently only works for Signals alerts.
type ListAlertsTagMatchStrategy string

const (
	ListAlertsTagMatchStrategyAny      ListAlertsTagMatchStrategy = "any"
	ListAlertsTagMatchStrategyMatchAll ListAlertsTagMatchStrategy = "match_all"
	ListAlertsTagMatchStrategyExclude  ListAlertsTagMatchStrategy = "exclude"
)

func (e ListAlertsTagMatchStrategy) ToPointer() *ListAlertsTagMatchStrategy {
	return &e
}
func (e *ListAlertsTagMatchStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "any":
		fallthrough
	case "match_all":
		fallthrough
	case "exclude":
		*e = ListAlertsTagMatchStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAlertsTagMatchStrategy: %v", v)
	}
}

type ListAlertsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// A text query for alerts
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// A comma separated list of user IDs. This currently only works for Signals alerts.
	Users *string `queryParam:"style=form,explode=true,name=users"`
	// A comma separated list of team IDs. This currently only works for Signals alerts.
	Teams *string `queryParam:"style=form,explode=true,name=teams"`
	// A comma separated list of signals rule IDs. This currently only works for Signals alerts.
	SignalRules *string `queryParam:"style=form,explode=true,name=signal_rules"`
	// A comma separated list of environment IDs. This currently only works for Signals alerts.
	Environments *string `queryParam:"style=form,explode=true,name=environments"`
	// A comma separated list of functionality IDs. This currently only works for Signals alerts.
	Functionalities *string `queryParam:"style=form,explode=true,name=functionalities"`
	// A comma separated list of service IDs. This currently only works for Signals alerts.
	Services *string `queryParam:"style=form,explode=true,name=services"`
	// A comma separated list of tags. This currently only works for Signals alerts.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
	// The strategy to match tags. `any` will return alerts that have at least one of the supplied tags, `match_all` will return only alerts that have all of the supplied tags, and `exclude` will only return alerts that have none of the supplied tags. This currently only works for Signals alerts.
	TagMatchStrategy *ListAlertsTagMatchStrategy `queryParam:"style=form,explode=true,name=tag_match_strategy"`
	// A comma separated list of statuses to filter by. Valid statuses are: opened, acknowledged, resolved, ignored, expired, linked, or snoozed
	Statuses *string `queryParam:"style=form,explode=true,name=statuses"`
	// When true, only returns alerts that have at least one associated incident. This currently only works for Signals alerts.
	HasAnyIncident *bool `queryParam:"style=form,explode=true,name=has_any_incident"`
	// Filters for alerts that started on or after the beginning of this date
	StartDate *time.Time `queryParam:"style=form,explode=true,name=start_date"`
	// Filters for alerts that started on or before the end of this date
	EndDate *time.Time `queryParam:"style=form,explode=true,name=end_date"`
	// Filters for alerts that started at or after this exact datetime
	StartDatetime *time.Time `queryParam:"style=form,explode=true,name=start_datetime"`
	// Filters for alerts that started at or before this exact datetime
	EndDatetime *time.Time `queryParam:"style=form,explode=true,name=end_datetime"`
}

func (l ListAlertsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAlertsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAlertsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAlertsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListAlertsRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListAlertsRequest) GetUsers() *string {
	if l == nil {
		return nil
	}
	return l.Users
}

func (l *ListAlertsRequest) GetTeams() *string {
	if l == nil {
		return nil
	}
	return l.Teams
}

func (l *ListAlertsRequest) GetSignalRules() *string {
	if l == nil {
		return nil
	}
	return l.SignalRules
}

func (l *ListAlertsRequest) GetEnvironments() *string {
	if l == nil {
		return nil
	}
	return l.Environments
}

func (l *ListAlertsRequest) GetFunctionalities() *string {
	if l == nil {
		return nil
	}
	return l.Functionalities
}

func (l *ListAlertsRequest) GetServices() *string {
	if l == nil {
		return nil
	}
	return l.Services
}

func (l *ListAlertsRequest) GetTags() *string {
	if l == nil {
		return nil
	}
	return l.Tags
}

func (l *ListAlertsRequest) GetTagMatchStrategy() *ListAlertsTagMatchStrategy {
	if l == nil {
		return nil
	}
	return l.TagMatchStrategy
}

func (l *ListAlertsRequest) GetStatuses() *string {
	if l == nil {
		return nil
	}
	return l.Statuses
}

func (l *ListAlertsRequest) GetHasAnyIncident() *bool {
	if l == nil {
		return nil
	}
	return l.HasAnyIncident
}

func (l *ListAlertsRequest) GetStartDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.StartDate
}

func (l *ListAlertsRequest) GetEndDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.EndDate
}

func (l *ListAlertsRequest) GetStartDatetime() *time.Time {
	if l == nil {
		return nil
	}
	return l.StartDatetime
}

func (l *ListAlertsRequest) GetEndDatetime() *time.Time {
	if l == nil {
		return nil
	}
	return l.EndDatetime
}
