// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type TestSlackChannelRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (t *TestSlackChannelRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}
