// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// NotFoundError - Status codes relating to the resource/entity they are requesting not being found or endpoints/routes not existing
type NotFoundError struct {
	Message              *string        `json:"message,omitzero"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

var _ error = &NotFoundError{}

func (e *NotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
