// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// UnauthorizedError - A collection of codes that generally means the client was not authenticated correctly for the request they want to make
type UnauthorizedError struct {
	Message              *string        `json:"message,omitzero"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

var _ error = &UnauthorizedError{}

func (e *UnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
