// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AIEntitiesPreferencesEntity - AI_Entities_PreferencesEntity model
type AIEntitiesPreferencesEntity struct {
	Ai                                        *bool `json:"ai,omitzero"`
	Description                               *bool `json:"description,omitzero"`
	Followups                                 *bool `json:"followups,omitzero"`
	Impact                                    *bool `json:"impact,omitzero"`
	Retros                                    *bool `json:"retros,omitzero"`
	SimilarIncidents                          *bool `json:"similar_incidents,omitzero"`
	SimilarIncidentsCooldownMinutes           *int  `json:"similar_incidents_cooldown_minutes,omitzero"`
	SimilarIncidentsMaxPerIncident            *int  `json:"similar_incidents_max_per_incident,omitzero"`
	Summaries                                 *bool `json:"summaries,omitzero"`
	ConferenceBridgeSummaryMinIntervalMinutes *int  `json:"conference_bridge_summary_min_interval_minutes,omitzero"`
	Updates                                   *bool `json:"updates,omitzero"`
}

func (a *AIEntitiesPreferencesEntity) GetAi() *bool {
	if a == nil {
		return nil
	}
	return a.Ai
}

func (a *AIEntitiesPreferencesEntity) GetDescription() *bool {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AIEntitiesPreferencesEntity) GetFollowups() *bool {
	if a == nil {
		return nil
	}
	return a.Followups
}

func (a *AIEntitiesPreferencesEntity) GetImpact() *bool {
	if a == nil {
		return nil
	}
	return a.Impact
}

func (a *AIEntitiesPreferencesEntity) GetRetros() *bool {
	if a == nil {
		return nil
	}
	return a.Retros
}

func (a *AIEntitiesPreferencesEntity) GetSimilarIncidents() *bool {
	if a == nil {
		return nil
	}
	return a.SimilarIncidents
}

func (a *AIEntitiesPreferencesEntity) GetSimilarIncidentsCooldownMinutes() *int {
	if a == nil {
		return nil
	}
	return a.SimilarIncidentsCooldownMinutes
}

func (a *AIEntitiesPreferencesEntity) GetSimilarIncidentsMaxPerIncident() *int {
	if a == nil {
		return nil
	}
	return a.SimilarIncidentsMaxPerIncident
}

func (a *AIEntitiesPreferencesEntity) GetSummaries() *bool {
	if a == nil {
		return nil
	}
	return a.Summaries
}

func (a *AIEntitiesPreferencesEntity) GetConferenceBridgeSummaryMinIntervalMinutes() *int {
	if a == nil {
		return nil
	}
	return a.ConferenceBridgeSummaryMinIntervalMinutes
}

func (a *AIEntitiesPreferencesEntity) GetUpdates() *bool {
	if a == nil {
		return nil
	}
	return a.Updates
}
