// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// AudiencesEntitiesAudienceShowEntity - Audiences_Entities_AudienceShowEntity model
type AudiencesEntitiesAudienceShowEntity struct {
	// Unique identifier for the audience
	ID *string `json:"id,omitzero"`
	// Name of the audience (maximum 255 characters)
	Name *string `json:"name,omitzero"`
	// Slug of the audience, unique and autogenerated
	Slug *string `json:"slug,omitzero"`
	// Description of the audience and its purpose (maximum 4000 characters)
	Description *string `json:"description,omitzero"`
	// Whether this is the organization's default audience
	Default *bool `json:"default,omitzero"`
	// When the audience was created
	CreatedAt *time.Time `json:"created_at,omitzero"`
	// When the audience was last updated
	UpdatedAt *time.Time `json:"updated_at,omitzero"`
	// When the audience was discarded (soft deleted)
	DiscardedAt *time.Time `json:"discarded_at,omitzero"`
	// List of incident details for this audience
	Details  []AudiencesEntitiesDetailEntity         `json:"details,omitzero"`
	Settings *NullableAudiencesEntitiesSettingEntity `json:"settings,omitzero"`
}

func (a AudiencesEntitiesAudienceShowEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudiencesEntitiesAudienceShowEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudiencesEntitiesAudienceShowEntity) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AudiencesEntitiesAudienceShowEntity) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AudiencesEntitiesAudienceShowEntity) GetSlug() *string {
	if a == nil {
		return nil
	}
	return a.Slug
}

func (a *AudiencesEntitiesAudienceShowEntity) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AudiencesEntitiesAudienceShowEntity) GetDefault() *bool {
	if a == nil {
		return nil
	}
	return a.Default
}

func (a *AudiencesEntitiesAudienceShowEntity) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AudiencesEntitiesAudienceShowEntity) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AudiencesEntitiesAudienceShowEntity) GetDiscardedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DiscardedAt
}

func (a *AudiencesEntitiesAudienceShowEntity) GetDetails() []AudiencesEntitiesDetailEntity {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *AudiencesEntitiesAudienceShowEntity) GetSettings() *NullableAudiencesEntitiesSettingEntity {
	if a == nil {
		return nil
	}
	return a.Settings
}
