// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateOnCallScheduleRotationOverride - Create an override covering a specific  time period in an on-call rotation, re-assigning that
// period to a specific user, or leaving it unassigned and claimable by any user, or even creating
// a purposeful gap in coverage if desired.
type CreateOnCallScheduleRotationOverride struct {
	// An ISO8601 time string specifying when the override should start.
	StartTime string `json:"start_time"`
	// An ISO8601 time string specifying when the override should end.
	EndTime string `json:"end_time"`
	// The ID of the user who should be on-call for the overridden period. If not provided, the override will be unassigned and claimable by any user.
	UserID *string `json:"user_id,omitzero"`
	// Whether or not the override should create a gap in coverage. If true, the override will result in the time window having no shifts present at all in the final schedule (defaults to false)
	IsGap *bool `json:"is_gap,omitzero"`
}

func (c *CreateOnCallScheduleRotationOverride) GetStartTime() string {
	if c == nil {
		return ""
	}
	return c.StartTime
}

func (c *CreateOnCallScheduleRotationOverride) GetEndTime() string {
	if c == nil {
		return ""
	}
	return c.EndTime
}

func (c *CreateOnCallScheduleRotationOverride) GetUserID() *string {
	if c == nil {
		return nil
	}
	return c.UserID
}

func (c *CreateOnCallScheduleRotationOverride) GetIsGap() *bool {
	if c == nil {
		return nil
	}
	return c.IsGap
}
