// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type CreateIncidentNoteVisibility string

const (
	CreateIncidentNoteVisibilityPrivateToOrg       CreateIncidentNoteVisibility = "private_to_org"
	CreateIncidentNoteVisibilityOpenToPublic       CreateIncidentNoteVisibility = "open_to_public"
	CreateIncidentNoteVisibilityInternalStatusPage CreateIncidentNoteVisibility = "internal_status_page"
)

func (e CreateIncidentNoteVisibility) ToPointer() *CreateIncidentNoteVisibility {
	return &e
}
func (e *CreateIncidentNoteVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private_to_org":
		fallthrough
	case "open_to_public":
		fallthrough
	case "internal_status_page":
		*e = CreateIncidentNoteVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateIncidentNoteVisibility: %v", v)
	}
}

type CreateIncidentNoteStatusPage struct {
	ID              string `json:"id"`
	IntegrationSlug string `json:"integration_slug"`
}

func (c *CreateIncidentNoteStatusPage) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateIncidentNoteStatusPage) GetIntegrationSlug() string {
	if c == nil {
		return ""
	}
	return c.IntegrationSlug
}

// CreateIncidentNote - Create a new note on for an incident. The visibility field on a note determines where it gets posted.
type CreateIncidentNote struct {
	Body string `json:"body"`
	// ISO8601 timestamp for when the note occurred
	OccurredAt  *time.Time                     `json:"occurred_at,omitzero"`
	Visibility  *CreateIncidentNoteVisibility  `default:"private_to_org" json:"visibility"`
	StatusPages []CreateIncidentNoteStatusPage `json:"status_pages,omitzero"`
	// When posting to a public status page, whether to also email its subscribers. Defaults to true.
	NotifyEmailSubscribers *bool `json:"notify_email_subscribers,omitzero"`
}

func (c CreateIncidentNote) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateIncidentNote) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateIncidentNote) GetBody() string {
	if c == nil {
		return ""
	}
	return c.Body
}

func (c *CreateIncidentNote) GetOccurredAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.OccurredAt
}

func (c *CreateIncidentNote) GetVisibility() *CreateIncidentNoteVisibility {
	if c == nil {
		return nil
	}
	return c.Visibility
}

func (c *CreateIncidentNote) GetStatusPages() []CreateIncidentNoteStatusPage {
	if c == nil {
		return nil
	}
	return c.StatusPages
}

func (c *CreateIncidentNote) GetNotifyEmailSubscribers() *bool {
	if c == nil {
		return nil
	}
	return c.NotifyEmailSubscribers
}
