// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// CurrentUserEntity model
type CurrentUserEntity struct {
	ID               *string                     `json:"id,omitzero"`
	Name             *string                     `json:"name,omitzero"`
	Source           *string                     `json:"source,omitzero"`
	Email            *string                     `json:"email,omitzero"`
	Role             *string                     `json:"role,omitzero"`
	Teams            []SuccinctEntity            `json:"teams,omitzero"`
	OrganizationID   *string                     `json:"organization_id,omitzero"`
	OrganizationName *string                     `json:"organization_name,omitzero"`
	AccountID        *int                        `json:"account_id,omitzero"`
	Region           *string                     `json:"region,omitzero"`
	Instance         *string                     `json:"instance,omitzero"`
	Organization     *NullableOrganizationEntity `json:"organization,omitzero"`
}

func (c CurrentUserEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CurrentUserEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CurrentUserEntity) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CurrentUserEntity) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CurrentUserEntity) GetSource() *string {
	if c == nil {
		return nil
	}
	return c.Source
}

func (c *CurrentUserEntity) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *CurrentUserEntity) GetRole() *string {
	if c == nil {
		return nil
	}
	return c.Role
}

func (c *CurrentUserEntity) GetTeams() []SuccinctEntity {
	if c == nil {
		return nil
	}
	return c.Teams
}

func (c *CurrentUserEntity) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CurrentUserEntity) GetOrganizationName() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationName
}

func (c *CurrentUserEntity) GetAccountID() *int {
	if c == nil {
		return nil
	}
	return c.AccountID
}

func (c *CurrentUserEntity) GetRegion() *string {
	if c == nil {
		return nil
	}
	return c.Region
}

func (c *CurrentUserEntity) GetInstance() *string {
	if c == nil {
		return nil
	}
	return c.Instance
}

func (c *CurrentUserEntity) GetOrganization() *NullableOrganizationEntity {
	if c == nil {
		return nil
	}
	return c.Organization
}
