// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type FunctionalityEntityLite struct {
	ID          *string    `json:"id,omitzero"`
	Name        *string    `json:"name,omitzero"`
	Slug        *string    `json:"slug,omitzero"`
	Description *string    `json:"description,omitzero"`
	CreatedAt   *time.Time `json:"created_at,omitzero"`
	UpdatedAt   *time.Time `json:"updated_at,omitzero"`
	// An object of label key and values
	Labels map[string]any `json:"labels,omitzero"`
	// List of active incident guids
	ActiveIncidents []string `json:"active_incidents,omitzero"`
	// List of links attached to this functionality.
	Links []LinksEntity           `json:"links,omitzero"`
	Owner *NullableTeamEntityLite `json:"owner,omitzero"`
	// Integer representing functionality tier (0-5, lower is more critical)
	ServiceTier           *int                  `json:"service_tier,omitzero"`
	AlertOnAdd            *bool                 `json:"alert_on_add,omitzero"`
	AutoAddRespondingTeam *bool                 `json:"auto_add_responding_team,omitzero"`
	UpdatedBy             *NullableAuthorEntity `json:"updated_by,omitzero"`
	// List of teams attached to the functionality
	Teams []TeamEntityLite `json:"teams,omitzero"`
}

func (f FunctionalityEntityLite) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionalityEntityLite) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionalityEntityLite) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FunctionalityEntityLite) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FunctionalityEntityLite) GetSlug() *string {
	if f == nil {
		return nil
	}
	return f.Slug
}

func (f *FunctionalityEntityLite) GetDescription() *string {
	if f == nil {
		return nil
	}
	return f.Description
}

func (f *FunctionalityEntityLite) GetCreatedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.CreatedAt
}

func (f *FunctionalityEntityLite) GetUpdatedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.UpdatedAt
}

func (f *FunctionalityEntityLite) GetLabels() map[string]any {
	if f == nil {
		return nil
	}
	return f.Labels
}

func (f *FunctionalityEntityLite) GetActiveIncidents() []string {
	if f == nil {
		return nil
	}
	return f.ActiveIncidents
}

func (f *FunctionalityEntityLite) GetLinks() []LinksEntity {
	if f == nil {
		return nil
	}
	return f.Links
}

func (f *FunctionalityEntityLite) GetOwner() *NullableTeamEntityLite {
	if f == nil {
		return nil
	}
	return f.Owner
}

func (f *FunctionalityEntityLite) GetServiceTier() *int {
	if f == nil {
		return nil
	}
	return f.ServiceTier
}

func (f *FunctionalityEntityLite) GetAlertOnAdd() *bool {
	if f == nil {
		return nil
	}
	return f.AlertOnAdd
}

func (f *FunctionalityEntityLite) GetAutoAddRespondingTeam() *bool {
	if f == nil {
		return nil
	}
	return f.AutoAddRespondingTeam
}

func (f *FunctionalityEntityLite) GetUpdatedBy() *NullableAuthorEntity {
	if f == nil {
		return nil
	}
	return f.UpdatedBy
}

func (f *FunctionalityEntityLite) GetTeams() []TeamEntityLite {
	if f == nil {
		return nil
	}
	return f.Teams
}
