// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type PublicAPIV1PermissionEntity struct {
	Slug                *string  `json:"slug,omitzero"`
	DisplayName         *string  `json:"display_name,omitzero"`
	Description         *string  `json:"description,omitzero"`
	CategoryDisplayName *string  `json:"category_display_name,omitzero"`
	CategorySlug        *string  `json:"category_slug,omitzero"`
	ParentSlug          *string  `json:"parent_slug,omitzero"`
	Required            *bool    `json:"required,omitzero"`
	Available           *bool    `json:"available,omitzero"`
	DependencySlugs     []string `json:"dependency_slugs,omitzero"`
}

func (p PublicAPIV1PermissionEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIV1PermissionEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIV1PermissionEntity) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *PublicAPIV1PermissionEntity) GetDisplayName() *string {
	if p == nil {
		return nil
	}
	return p.DisplayName
}

func (p *PublicAPIV1PermissionEntity) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicAPIV1PermissionEntity) GetCategoryDisplayName() *string {
	if p == nil {
		return nil
	}
	return p.CategoryDisplayName
}

func (p *PublicAPIV1PermissionEntity) GetCategorySlug() *string {
	if p == nil {
		return nil
	}
	return p.CategorySlug
}

func (p *PublicAPIV1PermissionEntity) GetParentSlug() *string {
	if p == nil {
		return nil
	}
	return p.ParentSlug
}

func (p *PublicAPIV1PermissionEntity) GetRequired() *bool {
	if p == nil {
		return nil
	}
	return p.Required
}

func (p *PublicAPIV1PermissionEntity) GetAvailable() *bool {
	if p == nil {
		return nil
	}
	return p.Available
}

func (p *PublicAPIV1PermissionEntity) GetDependencySlugs() []string {
	if p == nil {
		return nil
	}
	return p.DependencySlugs
}

// #region class-body-publicapiv1permissionentity
// #endregion class-body-publicapiv1permissionentity
