// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity struct {
	StartTime       *time.Time              `json:"start_time,omitzero"`
	EndTime         *time.Time              `json:"end_time,omitzero"`
	User            *NullableSuccinctEntity `json:"user,omitzero"`
	ID              *string                 `json:"id,omitzero"`
	CoverageRequest *string                 `json:"coverage_request,omitzero"`
	IsGap           *bool                   `json:"is_gap,omitzero"`
	CreatedAt       *time.Time              `json:"created_at,omitzero"`
}

func (s SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetStartTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartTime
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetEndTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndTime
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetUser() *NullableSuccinctEntity {
	if s == nil {
		return nil
	}
	return s.User
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetCoverageRequest() *string {
	if s == nil {
		return nil
	}
	return s.CoverageRequest
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetIsGap() *bool {
	if s == nil {
		return nil
	}
	return s.IsGap
}

func (s *SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}
