// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity - Signals_API_OnCallSchedulePreviewEntity_RotationPreviewEntity model
type SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity struct {
	Name           *string                                                           `json:"name,omitzero"`
	Color          *string                                                           `json:"color,omitzero"`
	OriginalShifts []SignalsAPIOnCallSchedulePreviewEntityOriginalShiftPreviewEntity `json:"original_shifts,omitzero"`
	Overrides      []SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity      `json:"overrides,omitzero"`
	Shifts         []SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity         `json:"shifts,omitzero"`
}

func (s SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetColor() *string {
	if s == nil {
		return nil
	}
	return s.Color
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetOriginalShifts() []SignalsAPIOnCallSchedulePreviewEntityOriginalShiftPreviewEntity {
	if s == nil {
		return nil
	}
	return s.OriginalShifts
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetOverrides() []SignalsAPIOnCallSchedulePreviewEntityOverridePreviewEntity {
	if s == nil {
		return nil
	}
	return s.Overrides
}

func (s *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetShifts() []SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity {
	if s == nil {
		return nil
	}
	return s.Shifts
}
