// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// UpdateIncidentLabels - Key:value pairs to track custom data for the incident
type UpdateIncidentLabels struct {
}

type UpdateIncidentCustomField struct {
	// The ID of the custom field you wish to set.
	FieldID string `json:"field_id"`
	// The value you wish to set on the custom field if the type of the field accepts string values
	ValueString *string `json:"value_string,omitzero"`
	// The value you wish to set on the custom field if the type of the field accepts array values
	ValueArray []string `json:"value_array,omitzero"`
}

func (u UpdateIncidentCustomField) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIncidentCustomField) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateIncidentCustomField) GetFieldID() string {
	if u == nil {
		return ""
	}
	return u.FieldID
}

func (u *UpdateIncidentCustomField) GetValueString() *string {
	if u == nil {
		return nil
	}
	return u.ValueString
}

func (u *UpdateIncidentCustomField) GetValueArray() []string {
	if u == nil {
		return nil
	}
	return u.ValueArray
}

// UpdateIncident - Updates an incident with provided parameters
type UpdateIncident struct {
	Name                  *string `json:"name,omitzero"`
	Summary               *string `json:"summary,omitzero"`
	CustomerImpactSummary *string `json:"customer_impact_summary,omitzero"`
	Description           *string `json:"description,omitzero"`
	// Key:value pairs to track custom data for the incident
	Labels              *UpdateIncidentLabels `json:"labels,omitzero"`
	Priority            *string               `json:"priority,omitzero"`
	Severity            *string               `json:"severity,omitzero"`
	SeverityConditionID *string               `json:"severity_condition_id,omitzero"`
	SeverityImpactID    *string               `json:"severity_impact_id,omitzero"`
	// List of tags for the incident
	TagList []string `json:"tag_list,omitzero"`
	// The ID of the incident type. This will copy values from the incident type (if any) unless they are being overridden via parameters in this request.
	IncidentTypeID *string `json:"incident_type_id,omitzero"`
	// An array of custom fields to set on the incident.
	CustomFields []UpdateIncidentCustomField `json:"custom_fields,omitzero"`
}

func (u UpdateIncident) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIncident) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateIncident) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateIncident) GetSummary() *string {
	if u == nil {
		return nil
	}
	return u.Summary
}

func (u *UpdateIncident) GetCustomerImpactSummary() *string {
	if u == nil {
		return nil
	}
	return u.CustomerImpactSummary
}

func (u *UpdateIncident) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateIncident) GetLabels() *UpdateIncidentLabels {
	if u == nil {
		return nil
	}
	return u.Labels
}

func (u *UpdateIncident) GetPriority() *string {
	if u == nil {
		return nil
	}
	return u.Priority
}

func (u *UpdateIncident) GetSeverity() *string {
	if u == nil {
		return nil
	}
	return u.Severity
}

func (u *UpdateIncident) GetSeverityConditionID() *string {
	if u == nil {
		return nil
	}
	return u.SeverityConditionID
}

func (u *UpdateIncident) GetSeverityImpactID() *string {
	if u == nil {
		return nil
	}
	return u.SeverityImpactID
}

func (u *UpdateIncident) GetTagList() []string {
	if u == nil {
		return nil
	}
	return u.TagList
}

func (u *UpdateIncident) GetIncidentTypeID() *string {
	if u == nil {
		return nil
	}
	return u.IncidentTypeID
}

func (u *UpdateIncident) GetCustomFields() []UpdateIncidentCustomField {
	if u == nil {
		return nil
	}
	return u.CustomFields
}
