// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// UpdateOnCallShift - NOTE: This endpoint is deprecated and overrides are now the only way to modify a schedule's shifts.
// For compatibility, this endpoint will simply create an override for the specified time window.
type UpdateOnCallShift struct {
	// The start time of the shift in ISO8601 format.
	StartTime *time.Time `json:"start_time,omitzero"`
	// The end time of the shift in ISO8601 format.
	EndTime *time.Time `json:"end_time,omitzero"`
	// The ID of the user who is on-call for the shift. If not provided, the shift will be unassigned.
	UserID *string `json:"user_id,omitzero"`
	// A description of why coverage is needed for this shift. If the shift is re-assigned, this will automatically be cleared unless provided again.
	CoverageRequest *string `json:"coverage_request,omitzero"`
}

func (u UpdateOnCallShift) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOnCallShift) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOnCallShift) GetStartTime() *time.Time {
	if u == nil {
		return nil
	}
	return u.StartTime
}

func (u *UpdateOnCallShift) GetEndTime() *time.Time {
	if u == nil {
		return nil
	}
	return u.EndTime
}

func (u *UpdateOnCallShift) GetUserID() *string {
	if u == nil {
		return nil
	}
	return u.UserID
}

func (u *UpdateOnCallShift) GetCoverageRequest() *string {
	if u == nil {
		return nil
	}
	return u.CoverageRequest
}
