name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SDK repo
        uses: actions/checkout@v3
          
      - name: Copy OpenAPI spec
        run: |
          mkdir -p .speakeasy
          curl -fS https://api.firehydrant.io/v1/swagger_doc | jq . > /tmp/local_swagger_doc.json
          bin/convert-to-openapi3.main.kts /tmp/local_swagger_doc.json > /tmp/local_openapi3_doc.json
          cp /tmp/local_openapi3_doc.json ${GITHUB_WORKSPACE}/openapi.json
          
      - name: Generate SDK
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          force: ${{ github.event.inputs.force }}
          mode: pr
          set_version: ${{ github.event.inputs.set_version }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
